import Database from "@tauri-apps/plugin-sql";
import {
	type AsyncBatchRemoteCallback,
	type AsyncRemoteCallback,
	drizzle,
} from "drizzle-orm/sqlite-proxy";
import * as schema from "./schema";

export const DB_CONNECTION_STRING = "sqlite:fin.db";

let sqliteInstance: Database | null = null;
let sqliteInitPromise: Promise<Database> | null = null;

/**
 * Checks whether the current runtime environment is inside the Tauri WebView.
 * Returns false during build-time SSR / prerendering or non-Tauri browser environments.
 */
export function isTauriEnvironment(): boolean {
	return (
		typeof window !== "undefined" &&
		("__TAURI_INTERNALS__" in window || "__TAURI__" in window)
	);
}

/**
 * Retrieves or initializes the singleton Tauri SQLite database instance.
 * Automatically resolves `fin.db` inside the OS-default app config/data directory.
 */
export async function getSqlite(): Promise<Database> {
	if (sqliteInstance) {
		return sqliteInstance;
	}

	if (sqliteInitPromise) {
		return sqliteInitPromise;
	}

	if (!isTauriEnvironment()) {
		throw new Error(
			"Cannot initialize Tauri SQLite database: Not running inside a Tauri environment.",
		);
	}

	sqliteInitPromise = (async () => {
		try {
			const instance = await Database.load(DB_CONNECTION_STRING);
			// Enable WAL mode and foreign key constraints
			await instance.execute("PRAGMA foreign_keys = ON;");
			await instance.execute("PRAGMA journal_mode = WAL;");
			sqliteInstance = instance;
			return instance;
		} catch (error) {
			sqliteInitPromise = null;
			throw error;
		}
	})();

	return sqliteInitPromise;
}

/**
 * Proxy query handler that executes queries generated by Drizzle ORM
 * against Tauri's native SQLite plugin (backed by sqlx).
 */
const queryCallback: AsyncRemoteCallback = async (sql, params, method) => {
	if (!isTauriEnvironment()) {
		// Return empty rows during static prerendering or non-Tauri contexts
		return { rows: [] };
	}

	const sqlite = await getSqlite();

	// Check if this is a query that returns rows (SELECT, PRAGMA) or non-run method
	const isSelectOrPragma = /^\s*(SELECT|PRAGMA)\b/i.test(sql);
	const expectsRows = method !== "run" || isSelectOrPragma;

	if (!expectsRows) {
		await sqlite.execute(sql, params);
		return { rows: [] };
	}

	// For SELECT queries or returning methods, fetch rows
	const rawRows = await sqlite.select<Record<string, unknown>[]>(sql, params);

	// Drizzle sqlite-proxy driver expects each row as an array of column values: [col1, col2, ...]
	// IndexMap in tauri-plugin-sql preserves the exact column order from the query
	const rowValues = rawRows.map((row) => Object.values(row));

	if (method === "get") {
		return { rows: (rowValues.length > 0 ? rowValues[0] : undefined) as any };
	}

	return { rows: rowValues };
};

const batchCallback: AsyncBatchRemoteCallback = async (queries) => {
	const results = [];
	for (const query of queries) {
		const result = await queryCallback(query.sql, query.params, query.method);
		results.push(result);
	}
	return results;
};

/**
 * Type-safe Drizzle ORM database instance configured with the Tauri SQLite proxy driver.
 */
export const db = drizzle(queryCallback, batchCallback, {
	schema,
});

/**
 * Initializes and verifies the database connection and tables.
 */
export async function initDatabase(): Promise<{
	initialized: boolean;
	accountCount: number;
}> {
	if (!isTauriEnvironment()) {
		return { initialized: false, accountCount: 0 };
	}

	const sqlite = await getSqlite();

	// Verify database connectivity by checking accounts count
	const countResult = await sqlite.select<{ count: number }[]>(
		'SELECT COUNT(*) as count FROM "accounts";',
	);
	const accountCount = countResult[0]?.count ?? 0;

	return {
		initialized: true,
		accountCount,
	};
}
