import { invoke } from "@tauri-apps/api/core";
import Database from "@tauri-apps/plugin-sql";
import {
	type AsyncBatchRemoteCallback,
	type AsyncRemoteCallback,
	drizzle,
} from "drizzle-orm/sqlite-proxy";
import * as schema from "./schema";

export const DB_CONNECTION_STRING = "sqlite:fin.db";

interface ProxyQueryResult {
	rows: unknown[][];
}

let sqliteInstance: Database | null = null;
let sqliteInitPromise: Promise<Database> | null = null;

/**
 * Checks whether the current runtime environment is inside the Tauri WebView.
 * Returns false during build-time SSR / prerendering or non-Tauri browser environments.
 */
export function isTauriEnvironment(): boolean {
	return (
		typeof window !== "undefined" &&
		("__TAURI_INTERNALS__" in window || "__TAURI__" in window)
	);
}

/**
 * Retrieves or initializes the singleton Tauri SQLite database instance.
 * Automatically resolves `fin.db` inside the OS-default app config/data directory.
 */
export async function getSqlite(): Promise<Database> {
	if (sqliteInstance) {
		return sqliteInstance;
	}

	if (sqliteInitPromise) {
		return sqliteInitPromise;
	}

	if (!isTauriEnvironment()) {
		throw new Error(
			"Cannot initialize Tauri SQLite database: Not running inside a Tauri environment.",
		);
	}

	sqliteInitPromise = (async () => {
		try {
			const instance = await Database.load(DB_CONNECTION_STRING);
			// Enable WAL mode and foreign key constraints on the SQLite database
			await instance.execute("PRAGMA foreign_keys = ON;");
			await instance.execute("PRAGMA journal_mode = WAL;");
			sqliteInstance = instance;
			return instance;
		} catch (error) {
			sqliteInitPromise = null;
			throw error;
		}
	})();

	return sqliteInitPromise;
}

/**
 * Proxy query handler that executes queries generated by Drizzle ORM
 * against Tauri's native SQLite proxy commands (with raw positional row decoding).
 */
const queryCallback: AsyncRemoteCallback = async (sql, params, method) => {
	if (!isTauriEnvironment()) {
		// biome-ignore lint/suspicious/noExplicitAny: Drizzle sqlite-proxy requires undefined for get
		return { rows: (method === "get" ? undefined : []) as any };
	}

	// Ensure native SQLite database is loaded and WAL/PRAGMAs are executed
	await getSqlite();

	const res = await invoke<ProxyQueryResult>("proxy_query", {
		db: DB_CONNECTION_STRING,
		sql,
		params,
		method,
	});

	if (method === "get") {
		// biome-ignore lint/suspicious/noExplicitAny: Drizzle sqlite-proxy requires undefined for get
		return { rows: (res.rows.length > 0 ? res.rows[0] : undefined) as any };
	}

	return { rows: res.rows };
};

const batchCallback: AsyncBatchRemoteCallback = async (queries) => {
	if (!isTauriEnvironment()) {
		return queries.map((q) => ({
			// biome-ignore lint/suspicious/noExplicitAny: Drizzle sqlite-proxy requires undefined for get
			rows: (q.method === "get" ? undefined : []) as any,
		}));
	}

	// Ensure native SQLite database is loaded
	await getSqlite();

	const results = await invoke<ProxyQueryResult[]>("proxy_batch", {
		db: DB_CONNECTION_STRING,
		queries: queries.map((q) => ({
			sql: q.sql,
			params: q.params,
			method: q.method,
		})),
	});

	return results.map((res, i) => {
		const method = queries[i]?.method;
		if (method === "get") {
			// biome-ignore lint/suspicious/noExplicitAny: Drizzle sqlite-proxy requires undefined for get
			return { rows: (res.rows.length > 0 ? res.rows[0] : undefined) as any };
		}
		return { rows: res.rows };
	});
};

/**
 * Type-safe Drizzle ORM database instance configured with the Tauri SQLite proxy driver.
 */
export const db = drizzle(queryCallback, batchCallback, {
	schema,
});

/**
 * Initializes and verifies the database connection and tables.
 */
export async function initDatabase(): Promise<{
	initialized: boolean;
	accountCount: number;
}> {
	if (!isTauriEnvironment()) {
		return { initialized: false, accountCount: 0 };
	}

	await getSqlite();

	// Test end-to-end query execution through Drizzle
	const countResult = await db
		.select({ id: schema.accounts.id })
		.from(schema.accounts);

	return {
		initialized: true,
		accountCount: countResult.length,
	};
}
